# Generated by Django 4.1.2 on 2022-10-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='blog img'),
        ),
    ]
