# Generated by Django 4.1.2 on 2022-10-28 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
