# Generated by Django 4.1.2 on 2022-10-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_blog_created_at_blog_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='blogimg'),
        ),
    ]
